### PR TITLE
add Chinese document

### PR DESCRIPTION
**Pull request by tianzhijiexian**

### CODE REVIEW

**Comment by lukaseder** [comment]
Thank you very much for your contribution. While we really appreciate the effort and the intent, I'm afraid we won't be able to accept this contribution as we're maintaining our websites and documentation only in English.

In order to provide Chinese documentation to the jOOR community, I recommend you publish your translation in a blog post.

Thanks for your understanding.

**Comment by tianzhijiexian** [comment]
Could I push my blog with Chinese doc about jOOR.

**Comment by lukaseder** [comment]
Do you have your own blog? We don't have a Chinese blog either, only an English blog ...

**Comment by tianzhijiexian** [comment]
I have my own blog,maybe i can add a Chinese doc as a link below readme.md

**Pull request closed without merging**
