### PR TITLE
Improve test coverage

### PR DESCRIPTION
**Pull request by vbauer**

### CODE REVIEW

**Comment by lukaseder** [comment]
Sure, why not... Thanks a lot for your contribution!

**Comment by vbauer** [comment]
Thank you for merge!

**Comment by ooxi** [comment]
Is there a reason for not using [Test.expected](http://junit.sourceforge.net/javadoc/org/junit/Test.html#expected%28%29)?

**Comment by lukaseder** [comment]
Yes. The scope of `Test.expected` is a complete method. I like to put several tests inside of a method. I do hope that JUnit Lambda will add `assertThrows()`. Something like:

```java
    /**
     * Assert a Throwable type
     */
    public static void assertThrows(Class<?> throwable, ThrowableRunnable runnable) {
        assertThrows(throwable, runnable, t -> {});
    }

    /**
     * Assert a Throwable type and implement more assertions in a consumer
     */
    public static void assertThrows(Class<?> throwable, ThrowableRunnable runnable, Consumer<Throwable> exceptionConsumer) {
        boolean fail = false;
        try {
            runnable.run();
            fail = true;
        }
        catch (Throwable t) {
            if (!throwable.isInstance(t))
                throw new AssertionError("Bad exception type", t);

            exceptionConsumer.accept(t);
        }

        if (fail)
            Assert.fail("No exception was thrown. Expected: " + throwable.getName());
    }
```

**Comment by ooxi** [comment]
Thanks for the clarification :)

**Pull request merged**
