### PR TITLE
add Chinese document

### PR DESCRIPTION
**Pull request by tianzhijiexian**
增加了中文说明，update readme

### CODE REVIEW

**Comment by ooxi** [comment]
Could you describe the purpose of your patch?

**Comment by tianzhijiexian** [comment]
Give chinese people a quick way to use your project

**Comment by ooxi** [comment]
Normally you would add a second `README.md` with a chinese translation, not another example in a different language. The `README.md` already contains a couple of examples and if they are copied in every language in the same document it would be unmanageable.

**Comment by lukaseder** [comment]
Thank you @tianzhijiexian. I concur with @ooxi. While it would be helpful for non-English speakers to have documentation available about our products in other languages, we currently cannot set up the required infrastructure and personnel to maintain the foreign language documentation on a quality level that we would like to treat our users with. While at this point of time, your contribution might make sense - we may want to add additional documentation on the jooq.org website, which would then lack the Chinese counterparts.

Other projects that we're watching have accepted similar partial translations which the maintainers always struggled to keep in sync.

So, unfortunately, I will need to reject this pull request.

**Pull request closed without merging**
