### PR TITLE
Implemented #9

### PR DESCRIPTION
**Pull request by iirekm**

### CODE REVIEW

**Comment by lukaseder** [comment]
Wonderful, thank you very much. I'll review this later - in the meantime: Do you agree to contribute this under the terms of the Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0) ?

**Comment by iirekm** [comment]
yes, I agree

2015-02-19 10:52 GMT+01:00 Lukas Eder <notifications@github.com>:

**Comment by lukaseder** [comment]
If you want, feel free to add your name to all classes that you've modified via a Javadoc `@author` tag...

**Comment by iirekm** [comment]
I added @author, although I don't know if it's a good idea, it only adds a noise to java files. Now when we have Git, author can be easily found in Git history because Git history makes a difference between author and comitter .

**Comment by lukaseder** [comment]
Well, I don't think there's a `@contributor` tag in Javadoc. I think `@author` is fine for significant contributions. Note that this repository is just one instance of where the sources lie. jOOR is downloaded and shipped with other software, and contributor attribution is essential to OSS like this...

**Comment by lukaseder** [comment]
I have reverted the pull request (https://github.com/jOOQ/jOOR/pull/14) for now for a couple of reasons:

- There are dangerous changes (e.g. https://github.com/iirekm/jOOR/commit/431c58005a36bb3e8eb5a7f83ebd14b8caed9e91#commitcomment-9889715)
- There is a bit of noise in the changes (import reorderings, class renamings and other refactorings in the same commit, which makes it harder to review)

Do you want to give this another shot or just wait until we implement this ourselves?

**Pull request merged**
